TEST_CASES = [
    {
        "name": "基本中式",
        "ingredients": ["雞蛋", "番茄", "白飯"],
        "servings": 2,
        "max_minutes": 20,
        "equipment": ["平底鍋"],
        "restrictions": [],
        "cuisine": "中式",
    },
    {
        "name": "僅微波爐",
        "ingredients": ["雞蛋", "馬鈴薯"],
        "servings": 1,
        "max_minutes": 15,
        "equipment": ["微波爐"],
        "restrictions": [],
        "cuisine": "中式",
    },
    {
        "name": "10分鐘限制",
        "ingredients": ["吐司", "雞蛋", "番茄"],
        "servings": 1,
        "max_minutes": 10,
        "equipment": ["平底鍋"],
        "restrictions": [],
        "cuisine": "西式",
    },
    {
        "name": "無麩質",
        "ingredients": ["雞肉", "白飯", "青花菜"],
        "servings": 2,
        "max_minutes": 30,
        "equipment": ["平底鍋"],
        "restrictions": ["無麩質"],
        "cuisine": "融合",
    },
    {
        "name": "蛋奶素",
        "ingredients": ["雞蛋", "牛奶", "馬鈴薯", "洋蔥"],
        "servings": 2,
        "max_minutes": 30,
        "equipment": ["平底鍋"],
        "restrictions": ["蛋奶素"],
        "cuisine": "西式",
    },
    {
        "name": "花生過敏",
        "ingredients": ["雞胸肉", "白飯", "青菜"],
        "servings": 2,
        "max_minutes": 25,
        "equipment": ["平底鍋"],
        "restrictions": ["花生過敏"],
        "cuisine": "中式",
    },
    {
        "name": "模糊食材",
        "ingredients": ["肉", "菜"],
        "servings": 2,
        "max_minutes": 30,
        "equipment": ["平底鍋"],
        "restrictions": [],
        "cuisine": "中式",
    },
    {
        "name": "不合理超短時間",
        "ingredients": ["生雞腿", "馬鈴薯"],
        "servings": 4,
        "max_minutes": 5,
        "equipment": ["平底鍋"],
        "restrictions": [],
        "cuisine": "西式",
    },
    {
        "name": "中式轉西式",
        "ingredients": ["雞腿", "九層塔", "蒜"],
        "servings": 2,
        "max_minutes": 35,
        "equipment": ["平底鍋"],
        "restrictions": [],
        "cuisine": "西式",
    },
    {
        "name": "西式轉中式",
        "ingredients": ["義大利麵", "番茄", "絞肉"],
        "servings": 2,
        "max_minutes": 35,
        "equipment": ["鍋子", "平底鍋"],
        "restrictions": [],
        "cuisine": "中式",
    },
    {
        "name": "乳製品過敏",
        "ingredients": ["雞胸肉", "番茄", "白飯"],
        "servings": 2,
        "max_minutes": 25,
        "equipment": ["平底鍋"],
        "restrictions": ["乳製品過敏"],
        "cuisine": "融合",
    },
    {
        "name": "純素",
        "ingredients": ["豆腐", "番茄", "菇類", "白飯"],
        "servings": 2,
        "max_minutes": 25,
        "equipment": ["平底鍋"],
        "restrictions": ["純素"],
        "cuisine": "中式",
    },
    {
        "name": "無蛋",
        "ingredients": ["馬鈴薯", "洋蔥", "番茄"],
        "servings": 3,
        "max_minutes": 30,
        "equipment": ["平底鍋"],
        "restrictions": ["雞蛋過敏"],
        "cuisine": "西式",
    },
    {
        "name": "低鹽",
        "ingredients": ["鮭魚", "青花菜", "白飯"],
        "servings": 2,
        "max_minutes": 30,
        "equipment": ["平底鍋"],
        "restrictions": ["低鹽"],
        "cuisine": "融合",
    },
    {
        "name": "沒有烤箱",
        "ingredients": ["馬鈴薯", "洋蔥", "菇類"],
        "servings": 4,
        "max_minutes": 30,
        "equipment": ["平底鍋"],
        "restrictions": ["純素"],
        "cuisine": "西式",
    },
    {
        "name": "只有電鍋",
        "ingredients": ["白飯", "雞肉", "香菇"],
        "servings": 3,
        "max_minutes": 40,
        "equipment": ["電鍋"],
        "restrictions": [],
        "cuisine": "中式",
    },
    {
        "name": "兩種過敏限制",
        "ingredients": ["豬肉", "高麗菜", "白飯"],
        "servings": 2,
        "max_minutes": 20,
        "equipment": ["平底鍋"],
        "restrictions": ["花生過敏", "乳製品過敏"],
        "cuisine": "中式",
    },
    {
        "name": "少量食材",
        "ingredients": ["雞蛋"],
        "servings": 1,
        "max_minutes": 15,
        "equipment": ["平底鍋"],
        "restrictions": [],
        "cuisine": "中式",
    },
    {
        "name": "多人份",
        "ingredients": ["雞胸肉", "洋蔥", "番茄", "白飯"],
        "servings": 6,
        "max_minutes": 45,
        "equipment": ["平底鍋", "電鍋"],
        "restrictions": [],
        "cuisine": "融合",
    },
    {
        "name": "多重限制",
        "ingredients": ["豆腐", "青花菜", "白飯"],
        "servings": 2,
        "max_minutes": 25,
        "equipment": ["平底鍋"],
        "restrictions": ["純素", "無麩質", "花生過敏"],
        "cuisine": "融合",
    },
]
